mkmall:
  outputs:
    dev:
      account: MRB53852
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: dbt_indu
      threads: 3
      type: snowflake
      user: Sachin
      warehouse: transform_wh
  target: dev

dbtcloud:
  outputs:
    dev:
      account: MRB53852
      database: analytics
      password: Sachin$123
      role: analyticsengineer
      schema: dbt_inp
      threads: 3
      type: snowflake
      user: Sachin
      warehouse: transform_wh
  target: dev

