sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: v_nations
      - name: nation_info
      - name: orders
      - name: lineitems
      - name: parts
      - name: stg_employees
      - name: nations
      - name: suppliers
      - name: partsupps
      
        config:
          freshness:
            warn_after: { count: 1, period: hour }
            error_after: { count: 1, period: hour }
          loaded_at_field: o_orderdate::timestamp_ntz
  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
        config:
          freshness:
            warn_after: { count: 1, period: hour }
            error_after: { count: 1, period: hour }
          loaded_at_field: o_orderdate::timestamp_ntz

  - name: src3
    database: analytics
    schema: dbt_indu
    tables:
      - name: stg_employees
