sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: v_nations
      - name: nation_info
      - name: orders
        config:
          freshness: 
            warn_after: {count: 1, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts
      - name: stg_employees
      - name: nations
      - name: suppliers
      - name: partsupps
      
        
  - name: src2
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
        

  - name: src3
    database: analytics
    schema: dbt_indu
    tables:
      - name: stg_employees
